spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:EMPTY}
    url: ${SPRING_DATASOURCE_URL:EMPTY}
    username: $${SPRING_DATASOURCE_USERNAME:EMPTY}
    password: ${SPRING_DATASOURCE_PASSWORD:EMPTY}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update